#!/usr/bin/env bash

## Post-install bare server setup

echo "" >> ~/.bashrc

echo 'alias l='\''ls --group-directories-first --time-style="+%d.%m.%Y %H:%M" --color=auto -hFX'\''' >> ~/.bashrc

echo 'alias ll='\''ls -l --group-directories-first --time-style="+%d.%m.%Y %H:%M" --color=auto -F'\''' >> ~/.bashrc

echo 'alias la='\''ls -la --group-directories-first --time-style="+%d.%m.%Y %H:%M" --color=auto -F'\''' >> ~/.bashrc

echo "alias ya='yy'" >> ~/.bashrc

echo "alias vim='nvim'" >> ~/.bashrc

echo "" >> ~/.bashrc

echo 'function yy() {
	local tmp="$(mktemp -t "yazi-cwd.XXXXXX")"
	yazi "$@" --cwd-file="$tmp"
	if cwd="$(cat -- "$tmp")" && [ -n "$cwd" ] && [ "$cwd" != "$PWD" ]; then
		builtin cd -- "$cwd"
	fi
	rm -f -- "$tmp"
}' >> ~/.bashrc

echo "" >> ~/.bashrc

mkdir ~/.config

apt update -y

apt full-upgrade -y

apt install git snapd kitty ripgrep fzf xclip gcc make unzip yarn nodejs npm -y

snap install nvim --classic

git clone https://github.com/pindjouf/dotfiles.git

cp -r dotfiles/bspwm/nvim ~/.config

curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh

echo "" >> ~/.bashrc

. ~/.cargo/env

rustup update

cargo install --locked yazi-fm yazi-cli

source ~/.bashrc
