#!/usr/bin/env bash

## Bare server setup

echo "alias l='ls --group-directories-first --time-style=+"%d.%m.%Y %H:%M" --color=auto -hFX'\n"\
"alias ll='ls -l --group-directories-first --time-style=+"%d.%m.%Y %H:%M" --color=auto -F'\n"\
"alias la='ls -la --group-directories-first --time-style=+"%d.%m.%Y %H:%M" --color=auto -F'\n" >> .bashrc

apt update -y

apt full-upgrade -y

apt install git snapd kitty ripgrep fzf xclip gcc make -y

curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
rustup update

cargo install --locked yazi-fm yazi-cli
