#!/usr/bin/env python3

import re
import sys

def main():
    if len(sys.argv) < 2:
        print("put a fookin argument")
        return

    hex_string = sys.argv[1]

    if not re.fullmatch('[0-9a-fA-F]+', hex_string):
        print("gotta be a hex value")
        return

    result = ' '.join(re.findall('[0-9a-fA-F]{1,4}', bin(int(hex_string, 16))[2:]))
    print(result)

if __name__ == "__main__":
    main()
